
import os
import json
import re

# The scraped list of 209 problems
REMOTE_PROBLEMS = [
  {"id":"176","title":"Second Highest Salary","difficulty":"Medium","url":"https://leetcode.com/problems/second-highest-salary"},
  {"id":"177","title":"Nth Highest Salary","difficulty":"Medium","url":"https://leetcode.com/problems/nth-highest-salary"},
  {"id":"178","title":"Rank Scores","difficulty":"Medium","url":"https://leetcode.com/problems/rank-scores"},
  {"id":"180","title":"Consecutive Numbers","difficulty":"Medium","url":"https://leetcode.com/problems/consecutive-numbers"},
  {"id":"184","title":"Department Highest Salary","difficulty":"Medium","url":"https://leetcode.com/problems/department-highest-salary"},
  {"id":"185","title":"Department Top Three Salaries","difficulty":"Hard","url":"https://leetcode.com/problems/department-top-three-salaries"},
  {"id":"262","title":"Trips and Users","difficulty":"Hard","url":"https://leetcode.com/problems/trips-and-users"},
  {"id":"534","title":"Game Play Analysis III","difficulty":"Medium","url":"https://leetcode.com/problems/game-play-analysis-iii"},
  {"id":"550","title":"Game Play Analysis IV","difficulty":"Medium","url":"https://leetcode.com/problems/game-play-analysis-iv"},
  {"id":"569","title":"Median Employee Salary","difficulty":"Hard","url":"https://leetcode.com/problems/median-employee-salary"},
  {"id":"570","title":"Managers with at Least 5 Direct Reports","difficulty":"Medium","url":"https://leetcode.com/problems/managers-with-at-least-5-direct-reports"},
  {"id":"571","title":"Find Median Given Frequency of Numbers","difficulty":"Hard","url":"https://leetcode.com/problems/find-median-given-frequency-of-numbers"},
  {"id":"574","title":"Winning Candidate","difficulty":"Medium","url":"https://leetcode.com/problems/winning-candidate"},
  {"id":"578","title":"Get Highest Answer Rate Question","difficulty":"Medium","url":"https://leetcode.com/problems/get-highest-answer-rate-question"},
  {"id":"579","title":"Find Cumulative Salary of an Employee","difficulty":"Hard","url":"https://leetcode.com/problems/find-cumulative-salary-of-an-employee"},
  {"id":"580","title":"Count Student Number in Departments","difficulty":"Medium","url":"https://leetcode.com/problems/count-student-number-in-departments"},
  {"id":"585","title":"Investments in 2016","difficulty":"Medium","url":"https://leetcode.com/problems/investments-in-2016"},
  {"id":"601","title":"Human Traffic of Stadium","difficulty":"Hard","url":"https://leetcode.com/problems/human-traffic-of-stadium"},
  {"id":"602","title":"Friend Requests II: Who Has the Most Friends","difficulty":"Medium","url":"https://leetcode.com/problems/friend-requests-ii-who-has-the-most-friends"},
  {"id":"608","title":"Tree Node","difficulty":"Medium","url":"https://leetcode.com/problems/tree-node"},
  {"id":"612","title":"Shortest Distance in a Plane","difficulty":"Medium","url":"https://leetcode.com/problems/shortest-distance-in-a-plane"},
  {"id":"614","title":"Second Degree Follower","difficulty":"Medium","url":"https://leetcode.com/problems/second-degree-follower"},
  {"id":"615","title":"Average Salary: Departments VS Company","difficulty":"Hard","url":"https://leetcode.com/problems/average-salary-departments-vs-company"},
  {"id":"618","title":"Students Report By Geography","difficulty":"Hard","url":"https://leetcode.com/problems/students-report-by-geography"},
  {"id":"626","title":"Exchange Seats","difficulty":"Medium","url":"https://leetcode.com/problems/exchange-seats"},
  {"id":"1045","title":"Customers Who Bought All Products","difficulty":"Medium","url":"https://leetcode.com/problems/customers-who-bought-all-products"},
  {"id":"1070","title":"Product Sales Analysis III","difficulty":"Medium","url":"https://leetcode.com/problems/product-sales-analysis-iii"},
  {"id":"1077","title":"Project Employees III","difficulty":"Medium","url":"https://leetcode.com/problems/project-employees-iii"},
  {"id":"1097","title":"Game Play Analysis V","difficulty":"Hard","url":"https://leetcode.com/problems/game-play-analysis-v"},
  {"id":"1098","title":"Unpopular Books","difficulty":"Medium","url":"https://leetcode.com/problems/unpopular-books"},
  {"id":"1107","title":"New Users Daily Count","difficulty":"Medium","url":"https://leetcode.com/problems/new-users-daily-count"},
  {"id":"1112","title":"Highest Grade For Each Student","difficulty":"Medium","url":"https://leetcode.com/problems/highest-grade-for-each-student"},
  {"id":"1126","title":"Active Businesses","difficulty":"Medium","url":"https://leetcode.com/problems/active-businesses"},
  {"id":"1127","title":"User Purchase Platform","difficulty":"Hard","url":"https://leetcode.com/problems/user-purchase-platform"},
  {"id":"1132","title":"Reported Posts II","difficulty":"Medium","url":"https://leetcode.com/problems/reported-posts-ii"},
  {"id":"1149","title":"Article Views II","difficulty":"Medium","url":"https://leetcode.com/problems/article-views-ii"},
  {"id":"1158","title":"Market Analysis I","difficulty":"Medium","url":"https://leetcode.com/problems/market-analysis-i"},
  {"id":"1159","title":"Market Analysis II","difficulty":"Hard","url":"https://leetcode.com/problems/market-analysis-ii"},
  {"id":"1164","title":"Product Price at a Given Date","difficulty":"Medium","url":"https://leetcode.com/problems/product-price-at-a-given-date"},
  {"id":"1174","title":"Immediate Food Delivery II","difficulty":"Medium","url":"https://leetcode.com/problems/immediate-food-delivery-ii"},
  {"id":"1193","title":"Monthly Transactions I","difficulty":"Medium","url":"https://leetcode.com/problems/monthly-transactions-i"},
  {"id":"1194","title":"Tournament Winners","difficulty":"Hard","url":"https://leetcode.com/problems/tournament-winners"},
  {"id":"1204","title":"Last Person to Fit in the Bus","difficulty":"Medium","url":"https://leetcode.com/problems/last-person-to-fit-in-the-bus"},
  {"id":"1205","title":"Monthly Transactions II","difficulty":"Medium","url":"https://leetcode.com/problems/monthly-transactions-ii"},
  {"id":"1212","title":"Team Scores in Football Tournament","difficulty":"Medium","url":"https://leetcode.com/problems/team-scores-in-football-tournament"},
  {"id":"1225","title":"Report Contiguous Dates","difficulty":"Hard","url":"https://leetcode.com/problems/report-contiguous-dates"},
  {"id":"1264","title":"Page Recommendations","difficulty":"Medium","url":"https://leetcode.com/problems/page-recommendations"},
  {"id":"1270","title":"All People Report to the Given Manager","difficulty":"Medium","url":"https://leetcode.com/problems/all-people-report-to-the-given-manager"},
  {"id":"1285","title":"Find the Start and End Number of Continuous Ranges","difficulty":"Medium","url":"https://leetcode.com/problems/find-the-start-and-end-number-of-continuous-ranges"},
  {"id":"1308","title":"Running Total for Different Genders","difficulty":"Medium","url":"https://leetcode.com/problems/running-total-for-different-genders"},
  {"id":"1321","title":"Restaurant Growth","difficulty":"Medium","url":"https://leetcode.com/problems/restaurant-growth"},
  {"id":"1336","title":"Number of Transactions per Visit","difficulty":"Hard","url":"https://leetcode.com/problems/number-of-transactions-per-visit"},
  {"id":"1341","title":"Movie Rating","difficulty":"Medium","url":"https://leetcode.com/problems/movie-rating"},
  {"id":"1355","title":"Activity Participants","difficulty":"Medium","url":"https://leetcode.com/problems/activity-participants"},
  {"id":"1364","title":"Number of Trusted Contacts of a Customer","difficulty":"Medium","url":"https://leetcode.com/problems/number-of-trusted-contacts-of-a-customer"},
  {"id":"1369","title":"Get the Second Most Recent Activity","difficulty":"Hard","url":"https://leetcode.com/problems/get-the-second-most-recent-activity"},
  {"id":"1384","title":"Total Sales Amount by Year","difficulty":"Hard","url":"https://leetcode.com/problems/total-sales-amount-by-year"},
  {"id":"1393","title":"Capital Gain/Loss","difficulty":"Medium","url":"https://leetcode.com/problems/capital-gainloss"},
  {"id":"1398","title":"Customers Who Bought Products A and B but Not C","difficulty":"Medium","url":"https://leetcode.com/problems/customers-who-bought-products-a-and-b-but-not-c"},
  {"id":"1412","title":"Find the Quiet Students in All Exams","difficulty":"Hard","url":"https://leetcode.com/problems/find-the-quiet-students-in-all-exams"},
  {"id":"1440","title":"Evaluate Boolean Expression","difficulty":"Medium","url":"https://leetcode.com/problems/evaluate-boolean-expression"},
  {"id":"1445","title":"Apples & Oranges","difficulty":"Medium","url":"https://leetcode.com/problems/apples-oranges"},
  {"id":"1454","title":"Active Users","difficulty":"Medium","url":"https://leetcode.com/problems/active-users"},
  {"id":"1459","title":"Rectangles Area","difficulty":"Medium","url":"https://leetcode.com/problems/rectangles-area"},
  {"id":"1468","title":"Calculate Salaries","difficulty":"Medium","url":"https://leetcode.com/problems/calculate-salaries"},
  {"id":"1479","title":"Sales by Day of the Week","difficulty":"Hard","url":"https://leetcode.com/problems/sales-by-day-of-the-week"},
  {"id":"1501","title":"Countries You Can Safely Invest In","difficulty":"Medium","url":"https://leetcode.com/problems/countries-you-can-safely-invest-in"},
  {"id":"1532","title":"The Most Recent Three Orders","difficulty":"Medium","url":"https://leetcode.com/problems/the-most-recent-three-orders"},
  {"id":"1549","title":"The Most Recent Orders for Each Product","difficulty":"Medium","url":"https://leetcode.com/problems/the-most-recent-orders-for-each-product"},
  {"id":"1555","title":"Bank Account Summary","difficulty":"Medium","url":"https://leetcode.com/problems/bank-account-summary"},
  {"id":"1596","title":"The Most Frequently Ordered Products for Each Customer","difficulty":"Medium","url":"https://leetcode.com/problems/the-most-frequently-ordered-products-for-each-customer"},
  {"id":"1613","title":"Find the Missing IDs","difficulty":"Medium","url":"https://leetcode.com/problems/find-the-missing-ids"},
  {"id":"1635","title":"Hopper Company Queries I","difficulty":"Hard","url":"https://leetcode.com/problems/hopper-company-queries-i"},
  {"id":"1645","title":"Hopper Company Queries II","difficulty":"Hard","url":"https://leetcode.com/problems/hopper-company-queries-ii"},
  {"id":"1651","title":"Hopper Company Queries III","difficulty":"Hard","url":"https://leetcode.com/problems/hopper-company-queries-iii"},
  {"id":"1699","title":"Number of Calls Between Two Persons","difficulty":"Medium","url":"https://leetcode.com/problems/number-of-calls-between-two-persons"},
  {"id":"1709","title":"Biggest Window Between Visits","difficulty":"Medium","url":"https://leetcode.com/problems/biggest-window-between-visits"},
  {"id":"1715","title":"Count Apples and Oranges","difficulty":"Medium","url":"https://leetcode.com/problems/count-apples-and-oranges"},
  {"id":"1747","title":"Leetflex Banned Accounts","difficulty":"Medium","url":"https://leetcode.com/problems/leetflex-banned-accounts"},
  {"id":"1767","title":"Find the Subtasks That Did Not Execute","difficulty":"Hard","url":"https://leetcode.com/problems/find-the-subtasks-that-did-not-execute"},
  {"id":"1783","title":"Grand Slam Titles","difficulty":"Medium","url":"https://leetcode.com/problems/grand-slam-titles"},
  {"id":"1811","title":"Find Interview Candidates","difficulty":"Medium","url":"https://leetcode.com/problems/find-interview-candidates"},
  {"id":"1831","title":"Maximum Transaction Each Day","difficulty":"Medium","url":"https://leetcode.com/problems/maximum-transaction-each-day"},
  {"id":"1841","title":"League Statistics","difficulty":"Medium","url":"https://leetcode.com/problems/league-statistics"},
  {"id":"1843","title":"Suspicious Bank Accounts","difficulty":"Medium","url":"https://leetcode.com/problems/suspicious-bank-accounts"},
  {"id":"1853","title":"Convert Date Format","difficulty":"Easy","url":"https://leetcode.com/problems/convert-date-format"},
  {"id":"1867","title":"Orders With Maximum Quantity Above Average","difficulty":"Medium","url":"https://leetcode.com/problems/orders-with-maximum-quantity-above-average"},
  {"id":"1873","title":"Calculate Special Bonus","difficulty":"Easy","url":"https://leetcode.com/problems/calculate-special-bonus"},
  {"id":"1875","title":"Group Employees of the Same Salary","difficulty":"Medium","url":"https://leetcode.com/problems/group-employees-of-the-same-salary"},
  {"id":"1890","title":"The Latest Login in 2020","difficulty":"Easy","url":"https://leetcode.com/problems/the-latest-login-in-2020"},
  {"id":"1892","title":"Page Recommendations II","difficulty":"Hard","url":"https://leetcode.com/problems/page-recommendations-ii"},
  {"id":"1907","title":"Count Salary Categories","difficulty":"Medium","url":"https://leetcode.com/problems/count-salary-categories"},
  {"id":"1917","title":"Leetcodify Friends Recommendations","difficulty":"Hard","url":"https://leetcode.com/problems/leetcodify-friends-recommendations"},
  {"id":"1919","title":"Leetcodify Similar Friends","difficulty":"Hard","url":"https://leetcode.com/problems/leetcodify-similar-friends"},
  {"id":"1934","title":"Confirmation Rate","difficulty":"Medium","url":"https://leetcode.com/problems/confirmation-rate"},
  {"id":"1939","title":"Users That Actively Request Confirmation Messages","difficulty":"Easy","url":"https://leetcode.com/problems/users-that-actively-request-confirmation-messages"},
  {"id":"1949","title":"Strong Friendship","difficulty":"Medium","url":"https://leetcode.com/problems/strong-friendship"},
  {"id":"1951","title":"All the Pairs With the Maximum Number of Common Followers","difficulty":"Medium","url":"https://leetcode.com/problems/all-the-pairs-with-the-maximum-number-of-common-followers"},
  {"id":"1965","title":"Employees With Missing Information","difficulty":"Easy","url":"https://leetcode.com/problems/employees-with-missing-information"},
  {"id":"1972","title":"First and Last Call On the Same Day","difficulty":"Hard","url":"https://leetcode.com/problems/first-and-last-call-on-the-same-day"},
  {"id":"1978","title":"Employees Whose Manager Left the Company","difficulty":"Easy","url":"https://leetcode.com/problems/employees-whose-manager-left-the-company"},
  {"id":"1988","title":"Find Cutoff Score for Each School","difficulty":"Medium","url":"https://leetcode.com/problems/find-cutoff-score-for-each-school"},
  {"id":"1990","title":"Count the Number of Experiments","difficulty":"Medium","url":"https://leetcode.com/problems/count-the-number-of-experiments"},
  {"id":"2004","title":"The Number of Seniors and Juniors to Join the Company","difficulty":"Hard","url":"https://leetcode.com/problems/the-number-of-seniors-and-juniors-to-join-the-company"},
  {"id":"2010","title":"The Number of Seniors and Juniors to Join the Company II","difficulty":"Hard","url":"https://leetcode.com/problems/the-number-of-seniors-and-juniors-to-join-the-company-ii"},
  {"id":"2020","title":"Number of Accounts That Did Not Stream","difficulty":"Medium","url":"https://leetcode.com/problems/number-of-accounts-that-did-not-stream"},
  {"id":"2041","title":"Accepted Candidates From the Interviews","difficulty":"Medium","url":"https://leetcode.com/problems/accepted-candidates-from-the-interviews"},
  {"id":"2051","title":"The Category of Each Member in the Store","difficulty":"Medium","url":"https://leetcode.com/problems/the-category-of-each-member-in-the-store"},
  {"id":"2066","title":"Account Balance","difficulty":"Medium","url":"https://leetcode.com/problems/account-balance"},
  {"id":"2084","title":"Drop Type 1 Orders for Customers With Type 0 Orders","difficulty":"Medium","url":"https://leetcode.com/problems/drop-type-1-orders-for-customers-with-type-0-orders"},
  {"id":"2112","title":"The Airport With the Most Traffic","difficulty":"Medium","url":"https://leetcode.com/problems/the-airport-with-the-most-traffic"},
  {"id":"2118","title":"Build the Equation","difficulty":"Hard","url":"https://leetcode.com/problems/build-the-equation"},
  {"id":"2142","title":"The Number of Passengers in Each Bus I","difficulty":"Medium","url":"https://leetcode.com/problems/the-number-of-passengers-in-each-bus-i"},
  {"id":"2153","title":"The Number of Passengers in Each Bus II","difficulty":"Hard","url":"https://leetcode.com/problems/the-number-of-passengers-in-each-bus-ii"},
  {"id":"2159","title":"Order Two Columns Independently","difficulty":"Medium","url":"https://leetcode.com/problems/order-two-columns-independently"},
  {"id":"2173","title":"Longest Winning Streak","difficulty":"Hard","url":"https://leetcode.com/problems/longest-winning-streak"},
  {"id":"2175","title":"The Change in Global Rankings","difficulty":"Medium","url":"https://leetcode.com/problems/the-change-in-global-rankings"},
  {"id":"2199","title":"Finding the Topic of Each Post","difficulty":"Hard","url":"https://leetcode.com/problems/finding-the-topic-of-each-post"},
  {"id":"2228","title":"Users With Two Purchases Within Seven Days","difficulty":"Medium","url":"https://leetcode.com/problems/users-with-two-purchases-within-seven-days"},
  {"id":"2238","title":"Number of Times a Driver Was a Passenger","difficulty":"Medium","url":"https://leetcode.com/problems/number-of-times-a-driver-was-a-passenger"},
  {"id":"2252","title":"Dynamic Pivoting of a Table","difficulty":"Hard","url":"https://leetcode.com/problems/dynamic-pivoting-of-a-table"},
  {"id":"2253","title":"Dynamic Unpivoting of a Table","difficulty":"Hard","url":"https://leetcode.com/problems/dynamic-unpivoting-of-a-table"},
  {"id":"2292","title":"Products With Three or More Orders in Two Consecutive Years","difficulty":"Medium","url":"https://leetcode.com/problems/products-with-three-or-more-orders-in-two-consecutive-years"},
  {"id":"2298","title":"Tasks Count in the Weekend","difficulty":"Medium","url":"https://leetcode.com/problems/tasks-count-in-the-weekend"},
  {"id":"2308","title":"Arrange Table by Gender","difficulty":"Medium","url":"https://leetcode.com/problems/arrange-table-by-gender"},
  {"id":"2314","title":"The First Day of the Maximum Recorded Degree in Each City","difficulty":"Medium","url":"https://leetcode.com/problems/the-first-day-of-the-maximum-recorded-degree-in-each-city"},
  {"id":"2324","title":"Product Sales Analysis IV","difficulty":"Medium","url":"https://leetcode.com/problems/product-sales-analysis-iv"},
  {"id":"2346","title":"Compute the Rank as a Percentage","difficulty":"Medium","url":"https://leetcode.com/problems/compute-the-rank-as-a-percentage"},
  {"id":"2362","title":"Generate the Invoice","difficulty":"Hard","url":"https://leetcode.com/problems/generate-the-invoice"},
  {"id":"2372","title":"Calculate the Influence of Each Salesperson","difficulty":"Medium","url":"https://leetcode.com/problems/calculate-the-influence-of-each-salesperson"},
  {"id":"2388","title":"Change Null Values in a Table to the Previous Value","difficulty":"Medium","url":"https://leetcode.com/problems/change-null-values-in-a-table-to-the-previous-value"},
  {"id":"2394","title":"Employees With Deductions","difficulty":"Medium","url":"https://leetcode.com/problems/employees-with-deductions"},
  {"id":"2474","title":"Customers With Strictly Increasing Purchases","difficulty":"Hard","url":"https://leetcode.com/problems/customers-with-strictly-increasing-purchases"},
  {"id":"2494","title":"Merge Overlapping Events in the Same Hall","difficulty":"Hard","url":"https://leetcode.com/problems/merge-overlapping-events-in-the-same-hall"},
  {"id":"2686","title":"Immediate Food Delivery III","difficulty":"Medium","url":"https://leetcode.com/problems/immediate-food-delivery-iii"},
  {"id":"2688","title":"Find Active Users","difficulty":"Medium","url":"https://leetcode.com/problems/find-active-users"},
  {"id":"2701","title":"Consecutive Transactions with Increasing Amounts","difficulty":"Hard","url":"https://leetcode.com/problems/consecutive-transactions-with-increasing-amounts"},
  {"id":"2720","title":"Popularity Percentage","difficulty":"Hard","url":"https://leetcode.com/problems/popularity-percentage"},
  {"id":"2738","title":"Count Occurrences in Text","difficulty":"Medium","url":"https://leetcode.com/problems/count-occurrences-in-text"},
  {"id":"2752","title":"Customers with Maximum Number of Transactions on Consecutive Days","difficulty":"Hard","url":"https://leetcode.com/problems/customers-with-maximum-number-of-transactions-on-consecutive-days"},
  {"id":"2783","title":"Flight Occupancy and Waitlist Analysis","difficulty":"Medium","url":"https://leetcode.com/problems/flight-occupancy-and-waitlist-analysis"},
  {"id":"2793","title":"Status of Flight Tickets","difficulty":"Hard","url":"https://leetcode.com/problems/status-of-flight-tickets"},
  {"id":"2820","title":"Election Results","difficulty":"Medium","url":"https://leetcode.com/problems/election-results"},
  {"id":"2854","title":"Rolling Average Steps","difficulty":"Medium","url":"https://leetcode.com/problems/rolling-average-steps"},
  {"id":"2893","title":"Calculate Orders Within Each Interval","difficulty":"Medium","url":"https://leetcode.com/problems/calculate-orders-within-each-interval"},
  {"id":"2922","title":"Market Analysis III","difficulty":"Medium","url":"https://leetcode.com/problems/market-analysis-iii"},
  {"id":"2978","title":"Symmetric Coordinates","difficulty":"Medium","url":"https://leetcode.com/problems/symmetric-coordinates"},
  {"id":"2984","title":"Find Peak Calling Hours for Each City","difficulty":"Medium","url":"https://leetcode.com/problems/find-peak-calling-hours-for-each-city"},
  {"id":"2986","title":"Find Third Transaction","difficulty":"Medium","url":"https://leetcode.com/problems/find-third-transaction"},
  {"id":"2988","title":"Manager of the Largest Department","difficulty":"Medium","url":"https://leetcode.com/problems/manager-of-the-largest-department"},
  {"id":"2989","title":"Class Performance","difficulty":"Medium","url":"https://leetcode.com/problems/class-performance"},
  {"id":"2991","title":"Top Three Wineries","difficulty":"Hard","url":"https://leetcode.com/problems/top-three-wineries"},
  {"id":"2993","title":"Friday Purchases I","difficulty":"Medium","url":"https://leetcode.com/problems/friday-purchases-i"},
  {"id":"2994","title":"Friday Purchases II","difficulty":"Hard","url":"https://leetcode.com/problems/friday-purchases-ii"},
  {"id":"2995","title":"Viewers Turned Streamers","difficulty":"Hard","url":"https://leetcode.com/problems/viewers-turned-streamers"},
  {"id":"3050","title":"Pizza Toppings Cost Analysis","difficulty":"Medium","url":"https://leetcode.com/problems/pizza-toppings-cost-analysis"},
  {"id":"3052","title":"Maximize Items","difficulty":"Hard","url":"https://leetcode.com/problems/maximize-items"},
  {"id":"3054","title":"Binary Tree Nodes","difficulty":"Medium","url":"https://leetcode.com/problems/binary-tree-nodes"},
  {"id":"3055","title":"Top Percentile Fraud","difficulty":"Medium","url":"https://leetcode.com/problems/top-percentile-fraud"},
  {"id":"3056","title":"Snaps Analysis","difficulty":"Medium","url":"https://leetcode.com/problems/snaps-analysis"},
  {"id":"3057","title":"Employees Project Allocation","difficulty":"Hard","url":"https://leetcode.com/problems/employees-project-allocation"},
  {"id":"3058","title":"Friends With No Mutual Friends","difficulty":"Medium","url":"https://leetcode.com/problems/friends-with-no-mutual-friends"},
  {"id":"3060","title":"User Activities within Time Bounds","difficulty":"Hard","url":"https://leetcode.com/problems/user-activities-within-time-bounds"},
  {"id":"3061","title":"Calculate Trapping Rain Water","difficulty":"Hard","url":"https://leetcode.com/problems/calculate-trapping-rain-water"},
  {"id":"3087","title":"Find Trending Hashtags","difficulty":"Medium","url":"https://leetcode.com/problems/find-trending-hashtags"},
  {"id":"3089","title":"Find Bursty Behavior","difficulty":"Medium","url":"https://leetcode.com/problems/find-bursty-behavior"},
  {"id":"3103","title":"Find Trending Hashtags II","difficulty":"Hard","url":"https://leetcode.com/problems/find-trending-hashtags-ii"},
  {"id":"3118","title":"Friday Purchase III","difficulty":"Medium","url":"https://leetcode.com/problems/friday-purchase-iii"},
  {"id":"3124","title":"Find Longest Calls","difficulty":"Medium","url":"https://leetcode.com/problems/find-longest-calls"},
  {"id":"3126","title":"Server Utilization Time","difficulty":"Medium","url":"https://leetcode.com/problems/server-utilization-time"},
  {"id":"3140","title":"Consecutive Available Seats II","difficulty":"Medium","url":"https://leetcode.com/problems/consecutive-available-seats-ii"},
  {"id":"3156","title":"Employee Task Duration and Concurrent Tasks","difficulty":"Hard","url":"https://leetcode.com/problems/employee-task-duration-and-concurrent-tasks"},
  {"id":"3166","title":"Calculate Parking Fees and Duration","difficulty":"Medium","url":"https://leetcode.com/problems/calculate-parking-fees-and-duration"},
  {"id":"3182","title":"Find Top Scoring Students","difficulty":"Medium","url":"https://leetcode.com/problems/find-top-scoring-students"},
  {"id":"3188","title":"Find Top Scoring Students II","difficulty":"Hard","url":"https://leetcode.com/problems/find-top-scoring-students-ii"},
  {"id":"3204","title":"Bitwise User Permissions Analysis","difficulty":"Medium","url":"https://leetcode.com/problems/bitwise-user-permissions-analysis"},
  {"id":"3214","title":"Year on Year Growth Rate","difficulty":"Hard","url":"https://leetcode.com/problems/year-on-year-growth-rate"},
  {"id":"3220","title":"Odd and Even Transactions","difficulty":"Medium","url":"https://leetcode.com/problems/odd-and-even-transactions"},
  {"id":"3230","title":"Customer Purchasing Behavior Analysis","difficulty":"Medium","url":"https://leetcode.com/problems/customer-purchasing-behavior-analysis"},
  {"id":"3236","title":"CEO Subordinate Hierarchy","difficulty":"Hard","url":"https://leetcode.com/problems/ceo-subordinate-hierarchy"},
  {"id":"3252","title":"Premier League Table Ranking II","difficulty":"Medium","url":"https://leetcode.com/problems/premier-league-table-ranking-ii"},
  {"id":"3262","title":"Find Overlapping Shifts","difficulty":"Medium","url":"https://leetcode.com/problems/find-overlapping-shifts"},
  {"id":"3268","title":"Find Overlapping Shifts II","difficulty":"Hard","url":"https://leetcode.com/problems/find-overlapping-shifts-ii"},
  {"id":"3278","title":"Find Candidates for Data Scientist Position II","difficulty":"Medium","url":"https://leetcode.com/problems/find-candidates-for-data-scientist-position-ii"},
  {"id":"3293","title":"Calculate Product Final Price","difficulty":"Medium","url":"https://leetcode.com/problems/calculate-product-final-price"},
  {"id":"3308","title":"Find Top Performing Driver","difficulty":"Medium","url":"https://leetcode.com/problems/find-top-performing-driver"},
  {"id":"3322","title":"Premier League Table Ranking III","difficulty":"Medium","url":"https://leetcode.com/problems/premier-league-table-ranking-iii"},
  {"id":"3328","title":"Find Cities in Each State II","difficulty":"Medium","url":"https://leetcode.com/problems/find-cities-in-each-state-ii"},
  {"id":"3338","title":"Second Highest Salary II","difficulty":"Medium","url":"https://leetcode.com/problems/second-highest-salary-ii"},
  {"id":"3368","title":"First Letter Capitalization","difficulty":"Hard","url":"https://leetcode.com/problems/first-letter-capitalization"},
  {"id":"3374","title":"First Letter Capitalization II","difficulty":"Hard","url":"https://leetcode.com/problems/first-letter-capitalization-ii"},
  {"id":"3384","title":"Team Dominance by Pass Success","difficulty":"Hard","url":"https://leetcode.com/problems/team-dominance-by-pass-success"},
  {"id":"3390","title":"Longest Team Pass Streak","difficulty":"Hard","url":"https://leetcode.com/problems/longest-team-pass-streak"},
  {"id":"3401","title":"Find Circular Gift Exchange Chains","difficulty":"Hard","url":"https://leetcode.com/problems/find-circular-gift-exchange-chains"},
  {"id":"3421","title":"Find Students Who Improved","difficulty":"Medium","url":"https://leetcode.com/problems/find-students-who-improved"},
  {"id":"3451","title":"Find Invalid IP Addresses","difficulty":"Hard","url":"https://leetcode.com/problems/find-invalid-ip-addresses"},
  {"id":"3475","title":"DNA Pattern Recognition","difficulty":"Medium","url":"https://leetcode.com/problems/dna-pattern-recognition"},
  {"id":"3482","title":"Analyze Organization Hierarchy","difficulty":"Hard","url":"https://leetcode.com/problems/analyze-organization-hierarchy"},
  {"id":"3497","title":"Analyze Subscription Conversion","difficulty":"Medium","url":"https://leetcode.com/problems/analyze-subscription-conversion"},
  {"id":"3521","title":"Find Product Recommendation Pairs","difficulty":"Medium","url":"https://leetcode.com/problems/find-product-recommendation-pairs"},
  {"id":"3554","title":"Find Category Recommendation Pairs","difficulty":"Hard","url":"https://leetcode.com/problems/find-category-recommendation-pairs"},
  {"id":"3564","title":"Seasonal Sales Analysis","difficulty":"Medium","url":"https://leetcode.com/problems/seasonal-sales-analysis"},
  {"id":"3580","title":"Find Consistently Improving Employees","difficulty":"Medium","url":"https://leetcode.com/problems/find-consistently-improving-employees"},
  {"id":"3586","title":"Find COVID Recovery Patients","difficulty":"Medium","url":"https://leetcode.com/problems/find-covid-recovery-patients"},
  {"id":"3601","title":"Find Drivers with Improved Fuel Efficiency","difficulty":"Medium","url":"https://leetcode.com/problems/find-drivers-with-improved-fuel-efficiency"},
  {"id":"3611","title":"Find Overbooked Employees","difficulty":"Medium","url":"https://leetcode.com/problems/find-overbooked-employees"},
  {"id":"3617","title":"Find Students with Study Spiral Pattern","difficulty":"Hard","url":"https://leetcode.com/problems/find-students-with-study-spiral-pattern"},
  {"id":"3626","title":"Find Stores with Inventory Imbalance","difficulty":"Medium","url":"https://leetcode.com/problems/find-stores-with-inventory-imbalance"},
  {"id":"3642","title":"Find Books with Polarized Opinions","difficulty":"Medium","url":"https://leetcode.com/problems/find-books-with-polarized-opinions"},
  {"id":"3657","title":"Find Loyal Customers","difficulty":"Medium","url":"https://leetcode.com/problems/find-loyal-customers"},
  {"id":"3673","title":"Find Zombie Sessions","difficulty":"Hard","url":"https://leetcode.com/problems/find-zombie-sessions"},
  {"id":"3705","title":"Find Golden Hour Customers","difficulty":"Medium","url":"https://leetcode.com/problems/find-golden-hour-customers"},
  {"id":"3716","title":"Find Churn Risk Customers","difficulty":"Medium","url":"https://leetcode.com/problems/find-churn-risk-customers"},
  {"id":"3764","title":"Most Common Course Pairs","difficulty":"Hard","url":"https://leetcode.com/problems/most-common-course-pairs"},
  {"id":"3808","title":"Find Emotionally Consistent Users","difficulty":"Medium","url":"https://leetcode.com/problems/find-emotionally-consistent-users"}
]

BASE_DIR = "/Users/ejazanwar/Downloads/Interview/SQL/LeetCode_SQL"
SUB_DIRS = ["Easy", "Medium", "Hard"]

def get_local_problems():
    local_ids = set()
    for sub in SUB_DIRS:
        path = os.path.join(BASE_DIR, sub)
        if os.path.isdir(path):
            files = os.listdir(path)
            for f in files:
                match = re.match(r"^(\d+)_", f)
                if match:
                    local_ids.add(match.group(1))
    return local_ids

def main():
    local_ids = get_local_problems()
    
    missing_problems = []
    
    for prob in REMOTE_PROBLEMS:
        if prob["id"] not in local_ids:
            missing_problems.append(prob)
            
    # Output result as JSON for the agent to parse
    print(json.dumps(missing_problems, indent=2))
    
    print(f"Total Remote: {len(REMOTE_PROBLEMS)}", file=sys.stderr)
    print(f"Total Local: {len(local_ids)}", file=sys.stderr)
    print(f"Missing: {len(missing_problems)}", file=sys.stderr)

import sys
if __name__ == "__main__":
    main()
